# Generated by Django 5.0.1 on 2024-01-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dep_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dep_description', models.TextField()),
            ],
        ),
    ]
